# Generated by Django 5.2.1 on 2025-05-10 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_request_volunteer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Claimed', 'Claimed'), ('Delivered', 'Delivered')], max_length=20),
        ),
    ]
