# Generated by Django 5.2.1 on 2025-05-10 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_request_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Picked Up', 'Picked Up'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Expired', 'Expired')], max_length=20),
        ),
    ]
