# Generated by Django 5.2.1 on 2025-05-11 18:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_donation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 5, 1, 12, 0)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Claimed', 'Claimed'), ('In_Transit', 'In Transit'), ('Delivered', 'Delivered')], max_length=20),
        ),
    ]
