# Generated by Django 5.2.1 on 2025-05-11 20:14

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_request_created_at_alter_request_status'),
    ]

    # filepath: f:\Web Technologies\hunger-bridge\backend\api\migrations\0008_transaction_request.py
    operations = [
        migrations.AddField(
            model_name='transaction',
            name='request',
            field=models.ForeignKey(
                default=12,  # Use the request_id of the created Request object
                on_delete=models.CASCADE,
                to='api.request',
            ),
            preserve_default=False,
        ),
    ]
