# Generated by Django 5.2.1 on 2025-05-17 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_transaction_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='pickup_location',
            field=models.CharField(default='Unknown', max_length=500),
        ),
        migrations.AddField(
            model_name='ngo',
            name='ngo_location',
            field=models.CharField(default='Unknown', max_length=500),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='current_location',
            field=models.CharField(blank=True, default='Unknown', max_length=500, null=True),
        ),
    ]
