# Generated by Django 5.2.1 on 2025-05-17 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_ngo_user_alter_volunteer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='request',
            name='ngo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ngo_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
