# Generated by Django 5.2.1 on 2025-05-18 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_donation_pickup_location_ngo_ngo_location_and_more'),
        ('api', '0010_remove_request_created_at_alter_request_ngo'),
    ]

    operations = [
    ]
