# Generated by Django 5.2.1 on 2025-05-18 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_merge_20250518_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='request_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
