# Generated by Django 5.2.1 on 2025-05-09 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_request_ngo_alter_request_volunteer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='volunteer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volunteer_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
